title: Hello, world! I'm Johnny Romano
description: > # this means to ignore newlines until "baseurl:"
  Portfolio site
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Johnny Romano # add your name
author-img: johnny-romano.jpg # add your photo
about-author: Cybersecurity Analyst. Python Coder. USMC Vet. 🦅 # add description
twitter: johnpaulromano
instagram: _johnnyromano
github: johnpromano # add your Github handle
linkedin: johnnyromano
email: john.p.romano@gmail.com

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"
